name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: lint
        run: yarn lint
      - name: run unit test
        run: yarn test
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
